sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tiagovalentimbarreto/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tiagovalentimbarreto/react-test npm test

after_success:
  - docker build -t tiagovalentimbarreto/multi-client ./client
  - docker build -t tiagovalentimbarreto/multi-nginx ./nginx
  - docker build -t tiagovalentimbarreto/multi-server ./server
  - docker build -t tiagovalentimbarreto/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push tiagovalentimbarreto/multi-client
  - docker push tiagovalentimbarreto/multi-nginx
  - docker push tiagovalentimbarreto/multi-server
  - docker push tiagovalentimbarreto/multi-worker
    #deploy:
    #provider: elasticbeanstalk
    #region: us-west-1
    #app: multi-docker
    #env: MultiDocker-env
    #bucket_name: elasticbeanstalk-us-west-1-306476627547
    #bucket_path: docker-multi
    #on:
    #branch: master
    #access_key_id: $AWS_ACCESS_KEY
    #secret_access_key: $AWS_SECRET_KEY
